cloud:
  aws:
    credentials:
      accessKey: AKIAWHCFW3X6OPFH7YEI
      secretKey: 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
    s3:
      bucket: springboot-user-imagefile
    region:
      static: us-east-1
    stack:
      auto: false